---
all:
  children:
    webservers:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
    databases:
      hosts:
        localhost:
    loadbalancers:
      hosts:
        localhost:
  vars:
    deploy_environment: development
    ansible_become_pass: ""