#!/bin/bash

# Render Deployment Script for Django Flight Booking System
# This script helps deploy the application to Render cloud platform

set -e

echo "🚀 Django Flight Booking System - Render Deployment Helper"
echo "=========================================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

# Check if required files exist
echo ""
print_info "Checking deployment files..."

required_files=(
    "render.yaml"
    "build-render.sh"
    "requirements-render.txt"
    "capstone/settings_render.py"
    "Dockerfile.render"
)

missing_files=()
for file in "${required_files[@]}"; do
    if [[ -f "$file" ]]; then
        print_status "Found: $file"
    else
        print_error "Missing: $file"
        missing_files+=("$file")
    fi
done

if [[ ${#missing_files[@]} -gt 0 ]]; then
    print_error "Missing required files. Please ensure all files are present."
    exit 1
fi

# Check Python dependencies
echo ""
print_info "Checking Python environment..."

if command -v python3 &> /dev/null; then
    python_version=$(python3 --version)
    print_status "Python found: $python_version"
else
    print_error "Python 3 not found. Please install Python 3.11+"
    exit 1
fi

# Validate requirements file
echo ""
print_info "Validating requirements..."

if pip install --dry-run -r requirements-render.txt &> /dev/null; then
    print_status "Requirements validation passed"
else
    print_warning "Some requirements may have issues. Check requirements-render.txt"
fi

# Test build script
echo ""
print_info "Testing build script..."

if [[ -x "build-render.sh" ]]; then
    print_status "Build script is executable"
else
    print_warning "Making build script executable..."
    chmod +x build-render.sh
    print_status "Build script permissions fixed"
fi

# Validate Django settings
echo ""
print_info "Validating Django settings..."

export DJANGO_SETTINGS_MODULE=capstone.settings_render
if python3 manage.py check --settings=capstone.settings_render &> /dev/null; then
    print_status "Django settings validation passed"
else
    print_warning "Django settings validation failed. Check capstone/settings_render.py"
fi

# Check static files
echo ""
print_info "Checking static files setup..."

if [[ -d "static" ]]; then
    print_status "Static directory found"
else
    print_warning "Static directory not found. Creating..."
    mkdir -p static
    print_status "Static directory created"
fi

# Generate deployment summary
echo ""
print_info "Generating deployment summary..."

cat << EOF

📋 RENDER DEPLOYMENT SUMMARY
============================

🔧 Configuration Files:
   ✅ render.yaml - Main Render configuration
   ✅ render-mongodb.yaml - MongoDB-enabled configuration  
   ✅ build-render.sh - Build script
   ✅ requirements-render.txt - Python dependencies
   ✅ capstone/settings_render.py - Django settings
   ✅ Dockerfile.render - Docker configuration

🌐 Deployment Options:

   Option 1: Standard Deployment (PostgreSQL)
   ------------------------------------------
   File: render.yaml
   Database: PostgreSQL (Render managed)
   Cache: Redis (Render managed)
   
   Option 2: MongoDB Deployment
   ----------------------------
   File: render-mongodb.yaml
   Database: MongoDB (containerized)
   Cache: Redis (Render managed)

🚀 Deployment Steps:

   1. Push code to GitHub repository
   2. Connect repository to Render
   3. Choose deployment configuration:
      - For PostgreSQL: Use render.yaml
      - For MongoDB: Use render-mongodb.yaml
   4. Set environment variables in Render dashboard
   5. Deploy and monitor

🔑 Required Environment Variables:
   - SECRET_KEY (auto-generated by Render)
   - DEBUG=False
   - ALLOWED_HOSTS=.onrender.com,localhost
   - DATABASE_URL (auto-provided by Render for PostgreSQL)
   - MONGODB_URI (for MongoDB deployment)
   - REDIS_URL (auto-provided by Render)

📊 Service Configuration:
   - Web Service: Django application
   - Database: PostgreSQL or MongoDB
   - Cache: Redis
   - Static Files: WhiteNoise
   - Health Checks: /health/ endpoint

🔍 Monitoring:
   - Health Check: https://your-app.onrender.com/health/
   - Readiness Check: https://your-app.onrender.com/ready/
   - Admin Panel: https://your-app.onrender.com/admin/

EOF

# Final recommendations
echo ""
print_info "Final recommendations:"
echo ""
echo "1. 📁 Ensure your code is pushed to a GitHub repository"
echo "2. 🔗 Connect your GitHub repository to Render"
echo "3. 📝 Choose the appropriate render.yaml configuration"
echo "4. 🔐 Configure environment variables in Render dashboard"
echo "5. 🚀 Deploy and monitor the application"
echo "6. 🧪 Test the health endpoints after deployment"
echo ""

print_status "Render deployment preparation completed!"
print_info "Your Django Flight Booking System is ready for Render deployment! 🎉"

echo ""
echo "📚 Next Steps:"
echo "   1. Visit https://render.com and create an account"
echo "   2. Create a new Web Service from your GitHub repository"
echo "   3. Use the render.yaml file for automatic configuration"
echo "   4. Monitor the deployment logs and test the application"
echo ""

print_status "Good luck with your deployment! 🚀"