---
all:
  children:
    webservers:
      hosts:
        prod-web-01:
          ansible_host: 10.0.1.10
          ansible_user: ubuntu
        prod-web-02:
          ansible_host: 10.0.1.11
          ansible_user: ubuntu
        prod-web-03:
          ansible_host: 10.0.1.12
          ansible_user: ubuntu
    databases:
      hosts:
        prod-db-01:
          ansible_host: 10.0.2.10
          ansible_user: ubuntu
    loadbalancers:
      hosts:
        prod-lb-01:
          ansible_host: 10.0.3.10
          ansible_user: ubuntu
  vars:
    environment: production