#!/bin/bash
# Django Flight Booking Application Startup Script
# Generated by Ansible Deployment

cd /Users/sushant/Flight-Ticket-Booking/deployed
source /Users/sushant/Flight-Ticket-Booking/deployed/venv/bin/activate

echo "🚀 Starting Django Flight Booking Application"
echo "📁 Directory: /Users/sushant/Flight-Ticket-Booking/deployed"
echo "🐍 Python: $(which python)"
echo "🌐 URL: http://localhost:8000"
echo ""

python manage.py runserver 0.0.0.0:8000