---
all:
  children:
    webservers:
      hosts:
        staging-web-01:
          ansible_host: 10.0.1.20
          ansible_user: ubuntu
        staging-web-02:
          ansible_host: 10.0.1.21
          ansible_user: ubuntu
    databases:
      hosts:
        staging-web-01:  # Primary database server
    loadbalancers:
      hosts:
        staging-lb-01:
          ansible_host: 10.0.3.20
          ansible_user: ubuntu
  vars:
    environment: staging